# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AMM Notes
email: rerumnovarum@openmailbox.org
description: > # this means to ignore newlines until "baseurl:"
  Attempt to type some lecture notes in markdown and render them with gh-pages+jekyll
baseurl: "/ammnotes" # the subpath of your site, e.g. /blog
url: "https://rerumnovarum.github.io" # the base hostname & protocol for your site
github_username:  RerumNovarum

collections:
  pr:
        output: true
  de:
        output: true

# Build settings
markdown: kramdown

